### ISSUE TITLE
v3 개편사항

### ISSUE THREAD

**Issue by Hansanghyeon** [beeclover/articleT#109]
## TODOs

- [x] 해쉬태그 site title (wp)
- [x] header top - 광고성 배너로 변경
- [x] #98
- [x] top 버튼 추가
- [x] 포스트타입의 설명을 Option ACF로 빼기
	- [x] wp migration only ACF
- [x] #110
- [x] 검색후 페이지 undefined > 추천 포스트보이기
- [x] 메인배너 버튼 컨텐츠 등등 없어도 배너 등록가능하게
	- [x] wp migration only ACF
- [x] 로고 변경가능하게 수정 (wp)
- [x] PPT5/2 전페이지의 "포스트"라는 글자를 "아티클"로 모두 변경
- [ ] #113

**Comment by Seunghan-Lee** [comment]
@Hansanghyeon 
- PPT파일 5페이지 2번 : 전페이지의 "포스트"라는 글자를 "아티클"로 모두 변경하는 작업 추가 필요.
- 회사소개 페이지는 퍼블리싱 있을지 없을지 미결, 곧 결정날 듯.
