### ISSUE TITLE
메인개편기획

### ISSUE THREAD

**Issue by Hansanghyeon** [beeclover/articleT#74]
[20220119_아티클티 메인 개편 기획 V.02.pdf](https://github.com/beeclover/articleT/files/7933577/20220119_.V.02.pdf)

- [ ] `ppt1. x`
- [ ] `ppt2. x`
- [x] `ppt3. GNB` #75
- [x] `ppt4. 메인 롤링배너 가이드` #76
- [x] `ppt5. 메인 콘텐츠 영역` #76
- [x] `ppt6. 의견` #79
- [x] `ppt7. 메인 콘텐츠 영역` #76
- [x] `ppt8. 메인 콘텐츠 영역` #76
    - [x] 아카이브 (태그) #80
- [ ] `ppt9. ~~관리자 설정 방법 커스텀~~`
- [x] `ppt10. 메인 콘텐츠 영역` #76
- [x] `ppt11. 메인 콘텐츠 영역` #76
- [x] `ppt12. 메인 콘텐츠 영역` #76
- [x] `ppt13. 최신 포스트 페이지 추가` #77
- [x] `ppt14. 포스트 영역` #73
- [x] `ppt15. 카테고리 영역` #75
- [x] `ppt16. 카테고리 영역` #78
- [ ] `ppt17. x`
- [x] `ppt18. 오류 수정사항` #72
- [x] `ppt19. 오류 수정사항` #71
- [x] `ppt20. 오류 수정사항` #71

---

- [x] #88
- [ ] 어드민 개편 가이드 위키 작성
